version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Install"
          command: "npm install"
      - run:
          name: "Build"
          command: "npm run build"
      - run:
          name: "Done"
          command: "Echo \"Done\""

workflows:
  say-hello-workflow:
    jobs:
      - build
